releases:
- name: update-cloud-provider-ini
  version: 
addons:
- name: update-master
  jobs: 
  - name: update-master
    release: update-cloud-provider-ini
  include:
    jobs:
    - name: kube-apiserver
      release: kubo
- name: update-worker
  jobs: 
  - name: update-worker
    release: update-cloud-provider-ini
  include:
    jobs:
    - name: kubelet
      release: kubo
  