#! /bin/bash

cp -L /var/vcap/jobs/update-master/config/cloud-provider.ini /var/vcap/jobs/kube-apiserver/config/cloud-provider.ini
cp -L /var/vcap/jobs/update-master/config/cloud-provider.ini /var/vcap/jobs/kube-controller-manager/config/cloud-provider.ini